### ISSUE TITLE
Conditional bages not showing up

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-webui#1126]
## The problem

![efaafb3fa05e3a18eae93581189f046d5c7a8965](https://user-images.githubusercontent.com/68030498/124383416-9ec3c000-dccc-11eb-9102-017f655eece9.gif)

Pre-Conditions:
- Badges generated via oh-repeater, from string-array, defined in widget-properties
- For debugging i did add the true/false result of my code, inteded for visibility-condition of the badges

The Problem:
- After hitting refresh-button or initially open up the overview-page, two badges have the visibility-condition of TRUE but only one is shown
- After opening and returning from a RANDOM page, back to overview, the missing badge is there
No item state has changed and i did not trigger any rule ... only navigation to another page and back, shows up the badge
--> As i inially open my overview-page, i do not see the true state of my devices/items

Code for visitibilty-condition:
`visible: =items[props.badgeitm.split(";")[loop.int_idx]].state == props.badgecond.split(";")[loop.int_idx]`

Full code of widget: (without the additional label showing true/false for debugging reasons)
```
uid: cLink
tags:
  - link
  - page
  - card
props:
  parameters:
    - description: Text, to be shown as Link
      label: Title
      name: title
      required: false
      type: TEXT
    - description: "example: cPowerConsumption"
      label: Page
      name: link
      required: true
      type: TEXT
    - description: "example: /static/livingroom.jpg"
      label: Background-Image
      name: backgroundurl
      required: false
      type: TEXT
    - description: "example: Off_office;Focus_office;Cinema_office;Chill_office;Party_office;"
      label: Scene List
      name: scene
      required: false
      type: TEXT
    - description: "example: Fernseher;SleepTimer;"
      label: Badge Text List
      name: badgetxt
      required: false
      type: TEXT
    - description: "example: tv;wifi;"
      label: Badge Icon List
      name: badgeico
      required: false
      type: TEXT
    - description: "example: dSckBedRoomTv_Swt;dSckLvngRoomTv_Swt;"
      label: Badge Item List
      name: badgeitm
      required: false
      type: TEXT
    - description: "example: ON;ON;"
      label: Badge Condition List
      name: badgecond
      required: false
      type: TEXT
    - description: "example: green;orange;"
      label: Badge Color List
      name: badgecol
      required: false
      type: TEXT
  parameterGroups: []
timestamp: Jun 13, 2021, 9:38:23 AM
component: f7-card
config:
  style:
    padding: 0px
    border-radius: 7px
    border-width: 1px
    border-color: rgba(255,255,255, 0.2)
    box-shadow: 0px 0px 8px 4px rgba(255, 255, 255, 0.1)
  outline: true
slots:
  default:
    - component: f7-card-content
      config:
        style:
          height: 100px
          padding: 0px
          background-image: ='url(' + props.backgroundurl + ')'
          background-size: cover
          background-postion: center
          border-radius: inherit
      slots:
        default:
          - component: oh-button
            config:
              position: absolute
              action: navigate
              actionPage: ='page:' + props.link
              actionPageTransition: f7-circle
              border-radius: inherit
              style:
                --f7-button-bg-color: rgba(0,0,0,0.3)
                --f7-button-hover-bg-color: transparent
                --f7-button-pressed-bg-color: white
                height: 100%
                width: 100%
                top: 0px
                left: 0px
                padding: 0px
                border-radius: inherit
            slots:
              default:
                - component: oh-button
                  config:
                    style:
                      height: 100%
                      width: 100%
                      background: linear-gradient(20deg, rgba(255,255,255,0.5) 0%, rgba(255,255,255,0.5)5%, rgba(255,255,255,0) 30%,rgba(255,255,255,0) 70%,rgba(255,255,255,0.5) 95%, rgba(255,255,255,0.5) 100%)
          - component: Label
            config:
              text: "=(props.title) ? props.title : props.link"
              style:
                position: absolute
                font-size: 40px
                color: rgba(0,0,0,0.7)
                bottom: 0px
                left: 10px
                font-weight: bold
                pointer-events: none
                no-shadow: false
                text-shadow: 0px 0px 15px rgba(255, 255, 255, 1)
          - component: oh-button
            config:
              visible: =props.scene != NULL
              action: popup
              actionModal: widget:listScenes
              actionModalConfig:
                scenestr: =props.scene
              style:
                position: absolute
                right: 5px
                top: 5px
                width: 50px
                height: 50px
                padding: 0px
                --f7-button-hover-bg-color: rgba(255,255,255,0.5)
                display: flex
                justify-content: center
                flex-wrap: wrap
            slots:
              default:
                - component: f7-icon
                  config:
                    f7: slider_horizontal_3
                    color: black
                    size: 30px
    - component: oh-repeater
      config:
        for: int
        sourceType: array
        in: =props.badgetxt.split(";")
        filter: loop.int != ""
        fragment: true
      slots:
        default:
          - component: f7-badge
            config:
              visible: =items[props.badgeitm.split(";")[loop.int_idx]].state == props.badgecond.split(";")[loop.int_idx]
              textColor: black
              color: =props.badgecol.split(";")[loop.int_idx]
              style:
                justify-content: center
            slots:
              default:
                - component: f7-icon
                  config:
                    f7: =props.badgeico.split(";")[loop.int_idx]
                    size: 15px
                    color: black
                - component: Label
                  config:
                    text: =loop.int
```

## Expected behavior

Already at initial opening of the openHAB main UI, i see all the badges, where visibility should be true

## Steps to reproduce

1. Open main-page --> Badges are missing
2. Open random page and return to overview --> Badges are appearing

## Your environment

```yaml
runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.17-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 62140712
  totalMemory: 194904064
bindings:
  - astro
  - chromecast
  - http
  - mqtt
  - network
  - openweathermap
  - wifiled
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/78.0.3904.130 Safari/537.36
timestamp: 2021-07-04T11:45:57.803Z
```

## Browser console

```txt

```

## Additional information

I see this behaviour on several browsers
- Microsoft Edge
- Brave
- Through another Application, bundling communication-services

I think, that my usage is a relatively difficult implementation:
Widget-property-string, separated via semicolon --> Splitted string into array for oh-repeater --> oh-repeated badge-visibility-condition in dependency of item-name and -state, generated from splitted strings

But im pretty sure, that there is no fault in my implementation (as you see from debug-true/false-condition) and because everything shows as expected after returning from a random page.
To me (at the moment) this seems to be a UI-topic

I already have contacted OH-community, but no solution was found:
https://community.openhab.org/t/openhab-3-ui-badges-with-visible-condition-not-loaded-at-first/123405/8

**Comment by ghys** [comment]
I believe this was indeed fixed by #1177 so closing. If it isn't the case feel free to comment.

**Comment by SHU-red** [comment]
Hi there,
today i upgraded to
`openHAB 3.2.0.M4`
where i believe that your pull request was implemented in?

Sorry the behaviour is still the same.
As i open a sub-page and only go back (without touching any of the widgets) the "missing bagdes" appear
So i think i see the same behaviour as before.

As i tried it, i discovered something i did not test before:
- If im not logged in, **no additional badges appear**
- If im logged in, **the "missing badges" appear**

I whish i could provide you more info somehow.
Would it help if i create an additional video of the behaviour described above?
Are there any logs i can provide?

Maybe this behaviour is somehow my fault but i dont see where ...

```
runtimeInfo:
  version: 3.2.0.M4
  buildString: Milestone Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.10.63-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 100293752
  totalMemory: 194772992
bindings: []
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-11-08T17:41:17.802Z

```

**Comment by ghys** [comment]
I wouldn't be surprised if it ends up being a similar problem to #1199.
Try adding a `key: =Math.random().toString()` parameter (or anything unique enough) as suggested there to your f7-badge component and I'm 50+% sure it will fix the problem.

**Comment by SHU-red** [comment]
@ghys 
I think you are 100% correct

I could NOT solve the problem by adding
- key: =Math.random().toString()
- key: =Math.random() + vars.vis.toString
to the f7-badge, the oh-repeater or the oh-repeater-parent

But i could solve the problem by setting
- fragment = false

I don't know why i did this and what this option is exaclty for but now the appearance is as i expect it
--> All Badges are always shown

For me this is enough
If there is anything i can support just tell me

Thanks a lot for your time and effort
