### ISSUE TITLE
oh-gauge-card action not working, gauge not clickable

### ISSUE THREAD

**Issue by dandjo** [openhab/openhab-webui#2793]
## The problem

I’m using oh-gauge-cards to visualize my meters. Unfortunatelty, they are not clickable anywhere when using an action.

![image](https://github.com/user-attachments/assets/5b02069d-e53b-433f-a789-d50d51a2fb22)

## Expected behavior

Being able to klick on a gauge when an action is configured.

## Steps to reproduce

Configure a oh-gauge-card somewhere in the main UI.

```yml
component: oh-gauge-card
config:
  bgColor: "#ffffff"
  borderBgColor: "#cccccc"
  borderColor: "#006eff"
  borderWidth: "25"
  item: water_meter_value_day
  labelFontSize: "0"
  labelText: " "
  min: 0
  max: 0.5
  title: Water Meter Consumption
  type: semicircle
  valueFontSize: "22"
  action: analyzer
  actionAnalyzerItems:
    - water_meter_value_day
```

## Your environment

```yaml
runtimeInfo:
  version: 4.3.0
  buildString: "Build #4301"
locale: en-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.12
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 6.8.0-1012-raspi
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 168610088
  totalMemory: 662700032
  uptime: 88117
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-enigma2
  - binding-http
  - binding-mielecloud
  - binding-modbus
  - binding-mqtt
  - binding-netatmo
  - binding-tado
  - misc-openhabcloud
  - persistence-influxdb
  - transformation-jsonpath
  - transformation-regex
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-AT
    languages:
      - en-AT
      - en-GB
      - en-US
      - en
      - de
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/129.0.0.0 Safari/537.36
timestamp: 2024-10-03T13:59:18.259Z
```

**Comment by florian-h05** [comment]
Thanks for noticing this! Must have been caused by my refactoring in #2781.
I will fix that regression.

**Comment by dandjo** [comment]
Thanks @florian-h05 !
By the way, same applies to oh-image-card.

**Comment by florian-h05** [comment]
Fixed as well 👍

**Comment by dandjo** [comment]
Confirmed for oh-gauge-card, the oh-image-card still broken.

```yaml
component: oh-image-card
config:
  action: url
  actionUrl: http://water-meter.domotics.lan
  lazy: true
  lazyFadeIn: true
  refreshInterval: 10000
  url: http://water-meter.domotics.lan/img_tmp/alg_roi.jpg
```

**Comment by florian-h05** [comment]
oh-image-card fix just merged: #2795.

**Comment by dandjo** [comment]
Thanks, will test with next nightly.

**Comment by florian-h05** [comment]
FYI seems that Jenkins already build a new snapshot containing the fix.

**Comment by dandjo** [comment]
Perfect. Tested and confirmed. Thanks.
