### ISSUE TITLE
Showing password is no more possible for non editable things

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#3629]
Running OH 5.1 RC1.

Values for thing paramaters that have the "password" context are replaced by "***". This is normal.
But in the past, we had the ability to show the value.
This ability disappeared.

<img width="1462" height="140" alt="Image" src="https://github.com/user-attachments/assets/bc2f5304-f422-4cc3-ac77-e83b0e21f4f1" />

This is for a non editable thing.

**Comment by jsjames** [comment]
This was reported in #3613 (and fixed in #3614). I’m not sure if this got into rc1.

**Comment by holgerfriedrich** [comment]
According to the build info from
https://ci.openhab.org/view/Release%20Jobs/job/openhab-milestone/117/git-6/
it should have been included.

And I can confirm that the issue reported in #3613 is ok in RC2:

<img width="731" height="77" alt="Image" src="https://github.com/user-attachments/assets/bb291391-6058-41c0-a304-53e273039890" />

**Comment by lolodomo** [comment]
I just installed RC2 and I can confirm it is still missing.
I am running Firefox on Linux Mint.
My things are coming from YAML files.

**Comment by holgerfriedrich** [comment]
@lolodomo can you please describe where to find this password field?
And maybe you can double check my example (KNX-binding, add an KNX IP-interface, enable advanced options)?

**Comment by lolodomo** [comment]
Same with Chrome on my Android phone.

> can you please describe where to find this password field?

Any thing parameter that have the "password" context defined by developer.

They are properly detected by Main UI as ****** are displayed.
The problem is that I don't have the icon to reveal the real value.

**Comment by holgerfriedrich** [comment]
Chrome, now in normal settings (not advanced):
<img width="736" height="178" alt="Image" src="https://github.com/user-attachments/assets/9c814cdf-0de0-4553-8f04-0caa99a4a1fc" />

Anything visible on the JS console when loading the page?

**Comment by lolodomo** [comment]
No, anything except a 404 because there is no thing actions for this thing.

Did you check with a non editable thing ?

**Comment by holgerfriedrich** [comment]
Confirmed, it does not work for non-editable things on 5.1 RC2:

<img width="1613" height="522" alt="Image" src="https://github.com/user-attachments/assets/f595e4b7-3f42-4795-8ded-1ddfa5509cc5" />

It worked on 5.0:

<img width="750" height="195" alt="Image" src="https://github.com/user-attachments/assets/1a5aef6f-22a1-4921-8e2c-a51293e74368" />

**Comment by lolodomo** [comment]
@openhab/webui-maintainers : it is not really critical but in case you have time and it is easy to fix without any other  regression risk before @kaikreuzer  pushes the "start release build", that would be cool.

**Comment by florian-h05** [comment]
I agree that the risk for regressions is very low, and have created a fix.
