### ISSUE TITLE
[OH3.1 #2118]: Image element ignored/not being displayed

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-webui#763]
## The problem
When using image elements in basicUI which have been created via the sitemap generator in mainUI, these image elements won't be displayed.

## Expected behavior
Image elements should to be displayed in basicUI.

## Steps to reproduce
1. Create the following sitemap:
```
sitemap test label="Test" {
    Image url="https://www.openhab.org/openhab-logo-square.png"
}
```
2. Go to the page: http://_localIPaddress_:8080/basicui/app?sitemap=uicomponents_test
3. My current result:
![image](https://user-images.githubusercontent.com/22266373/103766167-a6a4ef00-501e-11eb-9bd8-e28993d2dce6.png)

## Your environment
```
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2118"
locale: de_AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 61027672
  totalMemory: 208728064
bindings:
  - amazonechocontrol
  - daikin
  - denonmarantz
  - exec
  - harmonyhub
  - http
  - ipcamera
  - mqtt
  - netatmo
  - network
  - ntp
  - systeminfo
  - unifi
  - wled
  - worxlandroid
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-US
      - en-AU
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-06T11:56:48.078Z
```
## Browser console
![image](https://user-images.githubusercontent.com/22266373/103766260-d18f4300-501e-11eb-9b62-90b378adc17d.png)

## Browser network traffic
![image](https://user-images.githubusercontent.com/22266373/103766309-e66bd680-501e-11eb-91fe-4a3e9c3d3cbd.png)

## Additional information
This problem only occurs in sitemaps being generated via mainUI; .sitemap files don't show this behaviour.
There is NO error message in the logfiles.

**Comment by ghys** [comment]
Basic UI HTML ouput:
```
<div class="mdl-form__control mdl-form__image" data-control-type="image" data-item=""
data-update-interval="0" data-widget-id="00"
data-proxied-url="../proxy?sitemap=null&amp;widgetId=00" data-valid-url="true" data-ignore-refresh="true">
		<img src="images/none.png">
	</div>
```
Note `sitemap=null`

`GET /rest/sitemaps/{sitemapId}` output:
```
{"name":"uicomponents_testimage","label":"Test Image","link":"http://localhost:8080/rest/sitemaps/uicomponents_testimage",
"homepage":{"id":"uicomponents_testimage","title":"Test Image","link":"http://localhost:8080/rest/sitemaps/uicomponents_testimage/uicomponents_testimage",
leaf":false,"timeout":false,"widgets":[{"widgetId":"00","type":"Image","visibility":true,
"label":"","icon":"","mappings":[],"url":"http://localhost:8080/proxy?sitemap\u003duicomponents_testimage.sitemap\u0026widgetId\u003d00","widgets":[]}]}}
```
`GET /proxy?sitemap=uicomponents_testimage.sitemap&widgetId=00` output:
```
HTTP ERROR 404
Problem accessing /proxy. Reason:

    Sitemap 'uicomponents_testimage.sitemap' could not be found!
```

So there are multiple things at play here:
- core adds .sitemap to the proxy URL (the sitemap isn't in a file)
- the ProxyServlet doesn't handle them properly
- Basic UI also replaces the invalid sitemap with null

**Comment by bigbasec** [comment]
This looks like it's going to be a core problem.  Traced it into ImageRenderer.java and we have this : 
`
String proxiedUrl = "../proxy?sitemap=" + sitemap + "&amp;widgetId=" + widgetId;

State state = itemUIRegistry.getState(w);
`

sitemap is = to null at this point, and state returns UNDEF.   

It then goes into this : 
`        if (!itemUIRegistry.getVisiblity(w)) {
            url = URL_NONE_ICON;
            ignoreRefresh = true;
        } else if (state instanceof RawType) {
            url = state.toFullString();
            ignoreRefresh = true;
        } else if ((sitemap != null) && ((state instanceof StringType) || validUrl)) {
            url = proxiedUrl + "&amp;t=" + (new Date()).getTime();
            ignoreRefresh = false;
        } else {
            url = URL_NONE_ICON;
            ignoreRefresh = true;
        }`

Which will set the url to the all else fails 'images/none.png'

**Comment by bigbasec** [comment]
As a workaround, if you create the same Image item in a file based sitemap it will work.   So it's something to do with how sitemaps that are generated in the UI are handled.

**Comment by bigbasec** [comment]
@ghys I don't think this is going to be a basic ui issue, as a sitemap loaded from a file works fine.   I've compared the generated sitemaps between a file loaded and a UI loaded and they are identical.   The issue I think is somewhere here : 
https://github.com/openhab/openhab-webui/blob/d7a80f359b52322f5f9b60933452d9a6a1757d18/bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ImageRenderer.java#L76

For a sitemap loaded via file, that null check passes and it then fetches it's sitemap value via : 
`sitemap = w.eResource().getURI().path();`

For anything done through the MainUI, that call is never made since w.eResource() is null, so the sitemap name is never there which is why an Image won't render.   It's actually not even loaded correctly, since hard coding a sitemap there fails as well with the proxy.   So I really think this might be something with how core loads the json.   The only 2 widgets that use(or check) eResource are the Image and Video.

**Comment by kaikreuzer** [comment]
> So there are multiple things at play here:

@ghys The first thing I actually notice that is at play here is that the Main UI defines a wrong name for the sitemap.

The sitemap code in the UI says:
´´´
sitemap page_42b7e1dec5 label="Test" {
```
while the Basic UI shows that the sitemap is actually provided under the name `uicomponents_page_42b7e1dec5`.
If you have a mismatch between the filename and the model name when reading a sitemap file, you will see a warning in the log - as no files are created when defining it through the UI, this problem isn't shown, but I guess it is the one that leads to the `sitemap=null` issue.

**Comment by Wikibear** [comment]
I have this issue also. There a some points more:

Sitemap via file:
static URL works - external not working
Sitemap via UI
static URL not working - external not working

**Comment by bigbasec** [comment]
> I have this issue also. There a some points more:
> 
> Sitemap via file:
> static URL works - external not working
> Sitemap via UI
> static URL not working - external not working
> 
> https://i.imgur.com/46STEg5.png

Fixes for this are already done, just need to wait for them to go through the build process.

**Comment by bigbasec** [comment]
Just reporting that the latest snapshot would is fixed from what I can tell.  Both file loaded sitemaps and UI generated ones both work.

**Comment by vcatini** [comment]
Now I see image elements both from file and web ui definition but just accessing them from the web client. I still can't see them from openhab Android client. Do you get the same? Is there any kind of procedure to make them working also in the android app? Thx

**Comment by Boby71** [comment]
Works for iOS app as well - thank you!
